# DataSource Config
spring:
  application:
    name: alipay
  datasource:
    # mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/shopping?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
server:
  port: 8082
alipay:
  appId: 9021000141680451
  appPrivateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDBrCX7wp1y9HI9hFME1a94wQBeEVNEvG/DihhiZjaO9DuZDqvE90ECLeRLz8p83DHtzNoz3gMfg5bfrUSG3Sf2arafS8POjb0LHYf6vMJWVWaJeuAMt6L3ey0cl8lCdd660vV2xfr87p0M7mMMtUnDIYL2+96UzwNvB3TgOzW9mTDCya1NHXNG8jSEpvYk9oSLlxTdqBW9wZnmFBFPf6QRPVARdFAJEvMxHipcs/8UDDbDxYPtXCIr4/3oHAKYqkyKy/cT+pAxwx59aV92o6FL+in1gdkm/4YXJQClaG/QOeVGTr2d3z5LsyiOsLMBs0SG/s9bCIA8xwkssjtM3sJTAgMBAAECggEBAJpuTLNd0fKyHM4Uz6YRRiRBsatQoVcz8uK3IQ6FdoezFDrNygX7Kqk0MtCI1muNoXp/WJb3NwJQCWQ+Y2AuxQjmusx2u6Hev5k3aRB0p3n0CxkhE7rQS3CPlb8xAVivaHUMdpLI94PsOOrww6aEgFbKSAXtfOSn1ZMZHQcX75hIRclp1kACmFGxQ2vb+TIskDf5iz7qlie5gujex1kxqUy9d21rsEMQ3vdhBe5kwqB/bnryC32MeU7ZuetvzuLMWeUF9kFqFbq5VpALM/XBlDC2AlC1hsdh2U1YMzNSLSF+0bHcUxoGSxmDeySb2bXSqAgPlZ7XdJ7zNYHijklhCLECgYEA4XlF5d+urkaifglvmAdzQMbJSDUaVHKakBDQQ13AD/7Aiyea4XG3+Ii25G8Jdhg8OqFCrNUDFryA1fyqnmyeQnPlaT9rAT4mP7BO9WY5himJBJ+6v0+XdW7p9XwQFcjBZUdm63/wISwjQZaFl34dJjx22UAn3F+4Xdj6EPqkkIUCgYEA2+SrpZjo+QFSk/qJzw0DznrQY8sFtf7XUAzZDKORnZ9zX14Nct564Tjgxp85QDsQqdprDzepNDc+CgCJ0yVW5ie2wV5Shh68gBJfeigi919BHP5scmCbtF5FfDA02lvn+vsfpHftbE7Xm3MS3eYb03u+/GSWxO2gMyAbCpFTqvcCgYBXl7lj2EYQRjiSJjBIK3zGyXMgriCQdgU9uopt4Vnf3OQIK1asBnWmA9apX8mZK0kardMtOYN9rbWPbB0Mdr30qvmQraZwUSiizWefRhtK14/3T+ZItC7u3CvfxlapX9hh9B8zlfw/ptn7fPJhLAk+9XZmZ9oUbss9CjH7rqOH0QKBgQDIULolMvUY0aGeeJ/N5LdRBASOxEZBkxQmMm4P23otszHw8Mcjm5UpUx1BE4+d+bCmavkYdcZIcQKtLexgUyWkqQ0NfpWC5MEnkpUzvRiNbVLtzMCSOXvehfqatXeQbCUaOGaM90tsXS6AyAWp65PxxksntaK7ZxWHPXok2Fr15QKBgD0/QfoRhKhiO94xEzVcS6gVtM3dTxX3dW+Og5SNN+91YG7gTWo13IaXkMhEmR5GIvzjpnbLAyMzuzU5JNSHYdS5xoUzB2xxhfRwl+Wl2G5RjyOK1g0Ynw7DXDH799fvo29zzywaNjQbd09VaBcPY9K3Ojw1ngZ4QGr3ahelMLAi
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAihmDd57PQpkUd8ENmbdVfZeCMTz3guvCkjkKpjPoFPvYY7huQIeIJirz+jBN6z4Ei3EKdcRiMoExlg0nLxpHxx60edD8AjnYNw4q87Mb08NPAgLpRXLdFftp9P+Sh08+URths/pqnFql6y8njpvNEt2EwzC81aqd30EEmC6NZDfya5LE9KiyJVyxQ5P85/4pUUXQ7jJFr29b0HL079PHsCmubM2eFogLzmQBsQSeDc2VkrxbwOQa/Gu2LM9uH7ypwxofsauUl+QqHjjpzX4MXqVdpGSMfeL++wsGE77XivPQt5mkfVZH8sOhbgiDKczwoIuSLz+idnWQomNGpf0/7wIDAQAB
  notifyUrl: http://frp.caodong0225.top:9527/alipay/notify